#survey
survey:
  url: /survey
  param: { module: survey, action: index }

#kousinkun
kousinkun_select:
  url: /kousinkun
  param: { module: kousinkun, action: select }

kousinkun_show:
  url: /kousinkun_show
  param: { module: kousinkun, action: show }

# default rules
homepage:
  url:   /
  param: { module: top, action: top }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
