#survey
survey:
  url: /survey
  param: { module: survey, action: index }

# default rules
homepage:
  url:   /
  param: { module: top, action: top }

default_symfony:
  url:   /symfony/:action/*
  param: { module: default }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
