default:
  http_metas:
    content-type: text/html

  metas:
    title:        赤坂ウェブサービス
    robots:       index, follow
    description:
    keywords:     赤坂, 楽天, rakuraku
    language:     ja

  stylesheets:    [anken, bootstrap, font-awesome, common]

  javascripts:    []

  has_layout:     on
  layout:         layout
